"""Init

Revision ID: 3282d63dc03d
Revises: dfac6fc5bf33
Create Date: 2024-06-05 20:17:55.808244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3282d63dc03d'
down_revision: Union[str, None] = 'dfac6fc5bf33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('providers', sa.Column('role', sa.Enum('admin', 'cook', 'barman', 'provider_bar', 'provider_kitchen', 'provider_universal', 'user', name='role'), nullable=True))
    op.add_column('users', sa.Column('name', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    op.drop_column('providers', 'role')
    # ### end Alembic commands ###
