"""Init

Revision ID: 73be43b2d69d
Revises: 8015952b1090
Create Date: 2024-09-25 08:56:00.826884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73be43b2d69d'
down_revision: Union[str, None] = '8015952b1090'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token_black_list', sa.Column('refresh_token', sa.String(length=255), nullable=False))
    op.drop_column('token_black_list', 'access_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token_black_list', sa.Column('access_token', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('token_black_list', 'refresh_token')
    # ### end Alembic commands ###
