"""Init

Revision ID: 769eaaca374e
Revises: b2e634d3946d
Create Date: 2024-05-06 15:50:48.072586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '769eaaca374e'
down_revision: Union[str, None] = 'b2e634d3946d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredients', sa.Column('store_id', sa.String(length=200), nullable=True))
    op.drop_constraint('ingredients_product_id_key', 'ingredients', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('ingredients_product_id_key', 'ingredients', ['product_id'])
    op.drop_column('ingredients', 'store_id')
    # ### end Alembic commands ###
