"""Init

Revision ID: a49875104736
Revises: ccf8bc4ceb7a
Create Date: 2024-10-03 12:47:11.845092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a49875104736'
down_revision: Union[str, None] = 'ccf8bc4ceb7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('premix_m2m_premix',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_premix_id', sa.Integer(), nullable=True),
    sa.Column('child_premix_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['child_premix_id'], ['premixes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_premix_id'], ['premixes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('premix_m2m_premix')
    # ### end Alembic commands ###
