"""Init

Revision ID: a7858c59fb37
Revises: 73d41597de23
Create Date: 2024-09-22 13:34:40.790708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7858c59fb37'
down_revision: Union[str, None] = '73d41597de23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dishes', sa.Column('ended', sa.Boolean(), nullable=True))
    op.drop_column('dishes', 'stop_list')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dishes', sa.Column('stop_list', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('dishes', 'ended')
    # ### end Alembic commands ###
