"""Init

Revision ID: b2e634d3946d
Revises: baa4cf8733b5
Create Date: 2024-05-03 16:19:18.494810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2e634d3946d'
down_revision: Union[str, None] = 'baa4cf8733b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ingredients_name_key', 'ingredients', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('ingredients_name_key', 'ingredients', ['name'])
    # ### end Alembic commands ###
