"""Init

Revision ID: dfac6fc5bf33
Revises: 4c4b99d1f994
Create Date: 2024-05-15 20:59:32.325531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfac6fc5bf33'
down_revision: Union[str, None] = '4c4b99d1f994'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dish_m2m_ingredient', sa.Column('quantity', sa.Float(), nullable=True))
    op.add_column('dish_m2m_premix', sa.Column('quantity', sa.Float(), nullable=True))
    op.add_column('dishes', sa.Column('runing_out', sa.Boolean(), nullable=True))
    op.add_column('ingredients', sa.Column('min_acceptable', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingredients', 'min_acceptable')
    op.drop_column('dishes', 'runing_out')
    op.drop_column('dish_m2m_premix', 'quantity')
    op.drop_column('dish_m2m_ingredient', 'quantity')
    # ### end Alembic commands ###
