"""Init

Revision ID: ef50501e00a0
Revises: 769eaaca374e
Create Date: 2024-05-06 21:03:31.752986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef50501e00a0'
down_revision: Union[str, None] = '769eaaca374e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('providers_chat_id_key', 'providers', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('providers_chat_id_key', 'providers', ['chat_id'])
    # ### end Alembic commands ###
