"""Init

Revision ID: fdd1be585226
Revises: ef50501e00a0
Create Date: 2024-05-11 19:24:03.942175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdd1be585226'
down_revision: Union[str, None] = 'ef50501e00a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingredients', 'store_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredients', sa.Column('store_id', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
